### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by nightfire445** [alpha1693/Bouncer#2]
ToDO
Backend

A user supplies the Bouncer server with contact information (email & phone number) used for alerts

Test: Email is verified upon registration
Test: Phone number is confirmed with SMS verification

Use Case: Changing Alert Preferences

Identifier: UC7

Description: A user wants to update his/her contact information for Bouncer alerts

Actors: User

Preconditions:
The user must be connected to the Internet
The user must be registered and email-verified with the Bouncer server
The user must be logged in

Flow of Events:
User browses to Bouncer user interface
User attempts to change his/her account information
User modifies the email address and/or phone number associated with the account
If the user changed the email address
    The user is instructed to confirm the account change by following a unique link sent to the new email 
    address
If the user changed the phone number
    The user is instructed to confirm the account change by entering a 4-digit verification code sent to the 
    new phone number

Postconditions:
    The user is prompted to make further changes to account preferences

**Comment by alpha1693** [comment]
Using django-notifications (https://github.com/django-notifications/django-notifications)

**Comment by nightfire445** [comment]
Sumit, Integrate authentication with your deliverable
